-- MySQL Script generated by MySQL Workbench
-- 07/29/15 21:13:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dmhp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dmhp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dmhp` DEFAULT CHARACTER SET utf8 ;
USE `dmhp` ;

-- -----------------------------------------------------
-- Table `dmhp`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dmhp`.`address` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `address` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `latitude` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `longitude` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dmhp`.`affiliation_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dmhp`.`affiliation_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `type` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dmhp`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dmhp`.`company` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(255) NOT NULL COMMENT '',
  `address_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_company_address1_idx` (`address_id` ASC)  COMMENT '',
  CONSTRAINT `fk_company_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `dmhp`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dmhp`.`home`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dmhp`.`home` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `address_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_home_address1_idx` (`address_id` ASC)  COMMENT '',
  CONSTRAINT `fk_home_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `dmhp`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dmhp`.`hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dmhp`.`hospital` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `address_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_hospital_address1_idx` (`address_id` ASC)  COMMENT '',
  CONSTRAINT `fk_hospital_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `dmhp`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dmhp`.`medical_school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dmhp`.`medical_school` (
  `id` INT(11) NOT NULL COMMENT '',
  `name` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `address_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_medical_school_address1_idx` (`address_id` ASC)  COMMENT '',
  CONSTRAINT `fk_medical_school_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `dmhp`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dmhp`.`physician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dmhp`.`physician` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `dob` DATE NULL DEFAULT NULL COMMENT '',
  `med_school_grad_year` YEAR NULL DEFAULT NULL COMMENT '',
  `med_specialty` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `philosophy` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `gender` CHAR(1) NULL DEFAULT NULL COMMENT '',
  `source` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dmhp`.`practice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dmhp`.`practice` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `address_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_practice_address1_idx` (`address_id` ASC)  COMMENT '',
  CONSTRAINT `fk_practice_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `dmhp`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dmhp`.`affiliation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dmhp`.`affiliation` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `physician_id` INT(11) NOT NULL COMMENT '',
  `hospital_id` INT(11) NOT NULL COMMENT '',
  `company_id` INT(11) NOT NULL COMMENT '',
  `practice_id` INT(11) NOT NULL COMMENT '',
  `medical_school_id` INT(11) NOT NULL COMMENT '',
  `home_id` INT(11) NOT NULL COMMENT '',
  `date_start` YEAR NULL DEFAULT NULL COMMENT '',
  `date_end` YEAR NULL DEFAULT NULL COMMENT '',
  `affiliation_type_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_affiliation_physician1_idx` (`physician_id` ASC)  COMMENT '',
  INDEX `fk_affiliation_hospital1_idx` (`hospital_id` ASC)  COMMENT '',
  INDEX `fk_affiliation_company1_idx` (`company_id` ASC)  COMMENT '',
  INDEX `fk_affiliation_practice1_idx` (`practice_id` ASC)  COMMENT '',
  INDEX `fk_affiliation_medical_school1_idx` (`medical_school_id` ASC)  COMMENT '',
  INDEX `fk_affiliation_home1_idx` (`home_id` ASC)  COMMENT '',
  INDEX `fk_affiliation_affiliation_type1_idx` (`affiliation_type_id` ASC)  COMMENT '',
  CONSTRAINT `fk_affiliation_affiliation_type1`
    FOREIGN KEY (`affiliation_type_id`)
    REFERENCES `dmhp`.`affiliation_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_affiliation_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `dmhp`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_affiliation_home1`
    FOREIGN KEY (`home_id`)
    REFERENCES `dmhp`.`home` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_affiliation_hospital1`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `dmhp`.`hospital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_affiliation_medical_school1`
    FOREIGN KEY (`medical_school_id`)
    REFERENCES `dmhp`.`medical_school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_affiliation_physician1`
    FOREIGN KEY (`physician_id`)
    REFERENCES `dmhp`.`physician` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_affiliation_practice1`
    FOREIGN KEY (`practice_id`)
    REFERENCES `dmhp`.`practice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dmhp`.`misc_note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dmhp`.`misc_note` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `home_id` INT(11) NOT NULL COMMENT '',
  `medical_school_id` INT(11) NOT NULL COMMENT '',
  `company_id` INT(11) NOT NULL COMMENT '',
  `address_id` INT(11) NOT NULL COMMENT '',
  `practice_id` INT(11) NOT NULL COMMENT '',
  `hospital_id` INT(11) NOT NULL COMMENT '',
  `physician_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_misc_note_home1_idx` (`home_id` ASC)  COMMENT '',
  INDEX `fk_misc_note_medical_school1_idx` (`medical_school_id` ASC)  COMMENT '',
  INDEX `fk_misc_note_company1_idx` (`company_id` ASC)  COMMENT '',
  INDEX `fk_misc_note_address1_idx` (`address_id` ASC)  COMMENT '',
  INDEX `fk_misc_note_practice1_idx` (`practice_id` ASC)  COMMENT '',
  INDEX `fk_misc_note_hospital1_idx` (`hospital_id` ASC)  COMMENT '',
  INDEX `fk_misc_note_physician1_idx` (`physician_id` ASC)  COMMENT '',
  CONSTRAINT `fk_misc_note_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `dmhp`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_misc_note_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `dmhp`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_misc_note_home1`
    FOREIGN KEY (`home_id`)
    REFERENCES `dmhp`.`home` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_misc_note_hospital1`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `dmhp`.`hospital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_misc_note_medical_school1`
    FOREIGN KEY (`medical_school_id`)
    REFERENCES `dmhp`.`medical_school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_misc_note_physician1`
    FOREIGN KEY (`physician_id`)
    REFERENCES `dmhp`.`physician` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_misc_note_practice1`
    FOREIGN KEY (`practice_id`)
    REFERENCES `dmhp`.`practice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE USER 'dmhp' IDENTIFIED BY 'dmhp';

GRANT ALL ON `mydb`.* TO 'dmhp';
GRANT ALL ON `dmhp`.* TO 'dmhp';
GRANT SELECT ON TABLE `mydb`.* TO 'dmhp';
GRANT SELECT ON TABLE `dmhp`.* TO 'dmhp';
GRANT SELECT, INSERT, TRIGGER ON TABLE `mydb`.* TO 'dmhp';
GRANT SELECT, INSERT, TRIGGER ON TABLE `dmhp`.* TO 'dmhp';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `mydb`.* TO 'dmhp';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `dmhp`.* TO 'dmhp';
GRANT EXECUTE ON ROUTINE `mydb`.* TO 'dmhp';
GRANT EXECUTE ON ROUTINE `dmhp`.* TO 'dmhp';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
